version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: slicercar-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: car
    ports:
      - "20055:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d car"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: slicercar-backend
    ports:
      - "30055:5000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:123456@postgres:5432/car
      - NODE_ENV=development

  importer:
    build:
      context: .
      dockerfile: docker/importer.Dockerfile
    container_name: slicercar-importer
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:123456@postgres:5432/car
    volumes:
      - ./mongo-backup:/app/mongo-backup:ro
      - ./backend:/app/backend:ro
      - ./docker/mongo_to_postgres_import.js:/app/mongo_to_postgres_import.js:ro
    command: ["node", "mongo_to_postgres_import.js", "--dir", "./mongo-backup", "--sync"]

  admin:
    build: ./admin-dashboard
    container_name: slicercar-admin
    ports:
      - "10055:10055"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:30055

  frontend:
    build:
      context: ./frontend
    container_name: slicercar-frontend
    ports:
      - "40055:40055"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgres-data:
