services:
  postgres:
    image: postgres:17
    container_name: slicercar-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${PG_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: slicercar-backend
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    container_name: slicercar-frontend
    env_file:
      - .env
    ports:
      - "${FRONT_END}:${FRONT_END}"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend

  admin:
    build: ./admin-dashboard
    container_name: slicercar-admin
    env_file:
      - .env
    ports:
      - "${ADMIN_PORT}:${ADMIN_PORT}"

  importer:
    build:
      context: .
      dockerfile: docker/importer.Dockerfile
    container_name: slicercar-importer
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./mongo-backup:/app/mongo-backup:ro
      - ./backend:/app/backend:ro
      - ./docker/mongo_to_postgres_import.js:/app/mongo_to_postgres_import.js:ro
    command: ["node", "mongo_to_postgres_import.js", "--dir", "./mongo-backup", "--sync"]

volumes:
  postgres-data:
